### PR TITLE
Add LICENSE file and update authors/contributorso

### PR DESCRIPTION
**Pull request by throughnothing**
Resolves issue #2

### CODE REVIEW

**Comment by throughnothing** [comment]
@sowbug @lizthegrey how does this look?

**Comment by lizthegrey** [comment]
Please attribute me as Liz Fong-Jones elizabeth@ugcs.caltech.edu with website https://plus.google.com/+lizthegrey

**Comment by throughnothing** [comment]
Updated, thanks.

**Comment by sowbug** [comment]
LGTM

**Comment by lizthegrey** [comment]
One potential licensing issue I can think of is that the trezor libraries provided by the trezor manufacturer are LGPLv3.

**Comment by throughnothing** [comment]
@lizthegrey have we used any of their code? (I haven't)

**Comment by lizthegrey** [comment]
Haven't we indirectly used it by including the result of compiling their proto with protojs?

**Comment by lizthegrey** [comment]
Oh, interesting, you made a separate copy of the interface, whose names/constants are required for interop and non-copyrightable c.f. oracle v google. Cool. The original version imported the proto directly.

(hm, no, it looks like it's still generated via proto2js - @sowbug can you clarify? c.f. https://github.com/sowbug/trhid/commit/d653bcc9f5c5c87e814011d6d34f894213809148)

**Comment by throughnothing** [comment]
Oops

**Comment by throughnothing** [comment]
Hmmmm, yeah the protobufs are interesting.  I'm actually not sure how licensing works on that....

@lizthegrey yeah I didn't really change what was there too much.

**Comment by throughnothing** [comment]
https://github.com/trezor/chrome-extension

**Comment by lizthegrey** [comment]
https://github.com/trezor/chrome-extension/blob/master/lib/hid.js

That looks awfully familiar, heh. Well, it's good to know it was made into something officially supported.

**Comment by throughnothing** [comment]
They gave us all credit in the readme and the package.json

**Pull request closed without merging**
